### ISSUE TITLE
DX and Clean Code: Peer review by valtat

### ISSUE THREAD

**Issue by valtat** [stenvma81/rpghelper#2]
Upon opening the project, it is very quickly clear what the project is about. The name and the readme indicate it's about a tabletop RPG helper application made with Python, all in one sentence. The features described after are easy to understand and concise. When looking at the code itself, it is apparent that the project is in very early stages and there is barely any functionality implemented yet. 

_**Code structure and quality**_
The code is organized well for all intents and purposes. There is a src folder which contains the actual python file, which as flask initialized and one endpoint for the home page. It returns 'This will be a fine application' and doesn't do anything else yet. In the root folder of the project there is a readme and license files, which are clear and easy to read. At this stage of the project, there is not much else to comment. 

_**Commit analysis**_
There are three commits so far, and they have some minor changes to the project, such as updating readme.md and adding the license.txt file. However, the commit messages are clear and I believe they follow good commit rules.

_**Communication and Documentation**_
The documentation is pretty solid. It lays out the foundation for the application, which seems to be well thought. The features included (Account management, character creation and management, game map & game notes) are a good starting point for building the application. 

_**Suggestions for Improvement**_
The only suggestion I can give at this point is to work hard and make a good project =) But since we are at the beginning of creating projects in this course, I wouldn't worry too much.

**Comment by stenvma81** [comment]
Thanks for the review! It seems like Jontsu gave you the link to my main branch. The actual work is underway in the account_management branch and there is also a pull request.
